blog/urls.py
from django.urls import path
from blog.views import *
from blog.feeds import LatestEntriesFeed
app_name = 'blog'

urlpatterns = [
    path('' , blog_home_view , name= 'home'),
    path('<int:pid>' , blog_single_view , name= 'single'),
    path('category/<str:cat_name>' , blog_home_view , name= 'category'),
    path('tag/<str:tag_name>' , blog_home_view , name= 'tag'),
    path('author/<str:auth_name>' , blog_home_view , name= 'author'),
    path('search/' , blog_search , name= 'search'),
    path('rss/feed/', LatestEntriesFeed()),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from website.sitemaps import StaticViewSitemap
from blog.sitemaps import BlogSitemap
import debug_toolbar
from django.contrib.auth import views as auth_views

sitemaps = {
    "static": StaticViewSitemap,
    'blog': BlogSitemap
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls')),
    path('blog/', include('blog.urls')),
    path('accounts/',include('accounts.urls')),
    path('summernote/',include('django_summernote.urls')),
    path('captcha/', include('captcha.urls')),
    path("sitemap.xml", sitemap , {"sitemaps": sitemaps} , name="django.contrib.sitemaps.views.sitemap" , ),
    path('robots.txt',include('robots.urls')),
    path('__debug__/',include(debug_toolbar.urls)),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]
urlpatterns += static(settings.STATIC_URL,document_root = settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

website/urls.py
from django.urls import path
from website.views import *

app_name = 'website'

urlpatterns = [

    path('', home_view , name= 'index'),
    path('about', about_view , name= 'about'),
    path('contact', contact_view , name= 'contact'),
    path('test', test , name= 'test'),
    path('newsletter', newsletter_view , name= 'newsletter'),

]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager

class Category(models.Model):
    name = models.CharField(max_length=255)
    
    def __str__(self):
        return self.name
    
    
class Post(models.Model):
    author = models.ForeignKey(User,on_delete= models.SET_NULL , null=True) # inja age beja ( set_null ) mizashtim ( CASCADE ) kole post haye oon fard ham pak mikard vaghty oon fard acc ro delete mikard 
    image = models.ImageField(upload_to='blog/' , default= 'blog/default.jpg')
    title = models.CharField(max_length=255)
    content = models.TextField()
    category = models.ManyToManyField(Category) # inja null ya default nazashtim chon django mige midonam mitone null ham bashe pas dast nemizanim
    tags = TaggableManager()
    counted_view = models.IntegerField(default=0)
    status = models.BooleanField(default=False)
    login_required = models.BooleanField(default=False)
    published_date = models.DateTimeField(null=True)
    created_date = models.DateTimeField(auto_now_add= True)
    updated_date = models.DateTimeField(auto_now= True)  
    

# in modele neveshtan to sql hast bara gereftan tamam dade haye mojod    
# SELECT * FROM Post
# SELECT * FROM Post WHERE status = 1

    class Meta:
        ordering = ['-created_date']
#        verbose_name = 'پست'
#        verbose_name_plural = 'پست ها'
        
    def __str__(self):
        return " {} - {} ".format(self.title , self.id)
    
    def  get_absolute_url(self):                                 # in behtare chon baes mishe ke ye view this post to ghesmat admin bara post ha ijad shavad valy oon yeki nemikone in karo
        return reverse('blog:single',kwargs={'pid':self.id})     # ya in bashe ya oon location to sitemap blog

    
'''                                                                     
    def small_content(self):
        if len(self.content) <=100:      # in ham mishod valy khob to template kardam ino ke behtar va behine tar bood
            return self.content
        else:
            return self.content[:100] + ' , ....'
'''

class Comment(models.Model):
    post = models.ForeignKey(Post,on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    email = models.EmailField()
    subject = models.CharField(max_length=255)
    message = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)
    approved = models.BooleanField(default=False)
    
    class Meta:
        ordering = ['-created_date']
        
    def __str__(self):
        return " {} - {} ".format(self.name , self.id)
        

blog/forms.py
from django import forms
from blog.models import Comment
from captcha.fields import CaptchaField

class CommentForm(forms.ModelForm):
    
    class Meta:
        model = Comment
        fields = ['post','name','email','subject','message']
        

blog/views.py
from django.shortcuts import render , get_object_or_404 , redirect
from blog.models import Post , Comment
from django.utils import timezone
from django.core.paginator import Paginator , PageNotAnInteger , EmptyPage
from blog.forms import CommentForm
from django.contrib import messages

def blog_home_view(request,cat_name=None,auth_name = None,tag_name = None):
    posts = Post.objects.filter(published_date__lte = timezone.now() , status =1)
    
    if cat_name:
        posts = posts.filter(category__name = cat_name)
    if auth_name:
        posts = posts.filter(author__username = auth_name)                 
    if tag_name:
        posts = posts.filter(tags__name__in=[tag_name])

    
    posts = Paginator(posts,2)
    try:
        page_number = request.GET.get('page')
        posts = posts.get_page(page_number)
    except PageNotAnInteger:
        posts = posts.page(1)
    except EmptyPage:
        posts = posts.page(1)
    
    context = {'posts' : posts}
    return render(request , 'blog/blog-home.html' , context)


# in zir rah dovome hamin balayy hast ke age dost dashtim va benazaremon behtar bood mitoni onjory ham benevisim
'''
def blog_home_view(request,**kwargs):
    posts = Post.objects.filter(published_date__lte = timezone.now() , status =1)
    
    if kwargs.get('cat_name'):
        posts = posts.filter(category__name = kwargs['cat_name'])
    if kwargs.get('auth_name'):
        posts = posts.filter(author__username = kwargs['auth_name'])
        
    context = {'posts' : posts}
    return render(request , 'blog/blog-home.html' , context)
'''


def blog_single_view(request,pid):
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            form.save()
            messages.add_message(request,messages.SUCCESS,'your comment created successfully')
        else:
            messages.add_message(request,messages.ERROR,'your message had problem creating')
    posts = Post.objects.filter(published_date__lte = timezone.now() , status =1)
    post = get_object_or_404(posts,pk=pid)
    print("User authenticated:", request.user.is_authenticated)
    print("Post login_required:", post.login_required)
    print("Post id:", post.id)
    if post.login_required and not request.user.is_authenticated:
    # Post requires login but user not logged in → redirect to login
        return redirect('accounts:login')
            
    comments = Comment.objects.filter(post=post.id , approved=True)
    post.counted_view += 1
    post.save()  
    next_post = posts.filter(id__gt=post.id, status=1).order_by('published_date').first()
    prev_post = posts.filter(id__lt=post.id, status=1).order_by('-published_date').first()
    form = CommentForm()
    context = {'post' : post ,
            'next_post': next_post , 
            'prev_post': prev_post , 
            'comments' : comments ,
            'form' : form ,
    }       
    return render(request , 'blog/blog-single.html' , context )
    


def blog_category(request,cat_name):
    posts = Post.objects.filter(status = 1)
    posts = posts.filter(category__name = cat_name)
    context = {'posts' : posts}
    return render(request,'blog/blog-home.html',context)

def blog_search(request):
    posts = Post.objects.filter(status = 1)
    if request.method == 'GET':
        search_term = request.GET.get('s')
        if search_term:
            posts = posts.filter(title__icontains  = search_term )
             
    context = {'posts' : posts }
    return render(request , 'blog/blog-home.html' , context)

templates/blog/blog-ads.html
{% load static %}

<div class="single-sidebar-widget ads-widget">
    <a href="#"><img class="img-fluid" src="{% static 'img/blog/ads-banner.jpg' %}" alt="" /></a>
</div>

templates/blog/blog-home.html
{% extends 'base.html' %}
{% load static %}
{% load blog_tags %}
{% block content %}
  <!-- start banner Area -->
  <section class="banner-area relative blog-home-banner" id="home">
    <div class="overlay overlay-bg"></div>
    <div class="container">
      <div class="row d-flex align-items-center justify-content-center">
        <div class="about-content blog-header-content col-lg-12">
          <h1 class="text-white">Dude You’re Getting a Telescope</h1>
          <p class="text-white">There is a moment in the life of any aspiring astronomer that it is time to buy that first</p>
        </div>
      </div>
    </div>
  </section>
  <!-- End banner Area -->

  <!-- Start top-category-widget Area -->
  <section class="top-category-widget-area pt-90 pb-90">
    <div class="container">
      <div class="row">
        <div class="col-lg-4">
          <div class="single-cat-widget">
            <div class="content relative">
              <div class="overlay overlay-bg"></div>
              <a href="#" target="_blank">
                <div class="thumb">
                  <img class="content-image img-fluid d-block mx-auto" src="{% static 'img/blog/cat-widget1.jpg' %}" alt="" />
                </div>
                <div class="content-details">
                  <h4 class="content-title mx-auto text-uppercase">Social life</h4>
                  <span></span>
                  <p>Enjoy your social life together</p>
                </div>
              </a>
            </div>
          </div>
        </div>
        <div class="col-lg-4">
          <div class="single-cat-widget">
            <div class="content relative">
              <div class="overlay overlay-bg"></div>
              <a href="#" target="_blank">
                <div class="thumb">
                  <img class="content-image img-fluid d-block mx-auto" src="{% static 'img/blog/cat-widget2.jpg' %}" alt="" />
                </div>
                <div class="content-details">
                  <h4 class="content-title mx-auto text-uppercase">Politics</h4>
                  <span></span>
                  <p>Be a part of politics</p>
                </div>
              </a>
            </div>
          </div>
        </div>
        <div class="col-lg-4">
          <div class="single-cat-widget">
            <div class="content relative">
              <div class="overlay overlay-bg"></div>
              <a href="#" target="_blank">
                <div class="thumb">
                  <img class="content-image img-fluid d-block mx-auto" src="{% static 'img/blog/cat-widget3.jpg' %}" alt="" />
                </div>
                <div class="content-details">
                  <h4 class="content-title mx-auto text-uppercase">Food</h4>
                  <span></span>
                  <p>Let the food be finished</p>
                </div>
              </a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  <!-- End top-category-widget Area -->

  <!-- Start post-content Area -->
  <section class="post-content-area">
    <div class="container">
      <div class="row">
        <div class="col-lg-8 posts-list">
          {% for post in posts %}
          <div class="single-post row">
            <div class="col-lg-3 col-md-3 meta-details">
              <ul class="tags">
                {% for cat in post.category.all %}
                <li>
                  <a href="{% url 'blog:category' cat_name=cat.name %}">{{ cat.name }}</a>{% if not forloop.last %}, {% endif %}</a>
                </li>
                {% endfor %}
              </ul>
              <div class="user-details row">
                <p class="user-name col-lg-12 col-md-12 col-6">
                  <a href="{% url 'blog:author' auth_name=post.author.username %}">{{post.author.get_full_name}}</a> <span class="lnr lnr-user"></span>
                </p>
                <p class="date col-lg-12 col-md-12 col-6">
                  <a href="#">{{post.published_date|date:'m/d/Y'}}</a> <span class="lnr lnr-calendar-full"></span>
                </p>
                <p class="view col-lg-12 col-md-12 col-6">
                  <a href="#">{{post.counted_view}}</a> <span class="lnr lnr-eye"></span>
                </p>
                <p class="comments col-lg-12 col-md-12 col-6">
                  <a href="#">{% comments_count post.id%} Comments</a> <span class="lnr lnr-bubble"></span>
                </p>
              </div>
            </div>
            <div class="col-lg-9 col-md-9">
              <div class="feature-img">
                <img class="img-fluid" src="{{post.image.url}}" alt="" />
              </div>
              <a class="posts-title" href="{% url 'blog:single' pid=post.id %}"><h3>{{post.title}}</h3></a>
              <p class="excert">{{post.content|truncatewords:7}}</p>  <!--Truncatechars برای دربرگیری حروف و truncatewords برای در بر گیری تعداد کلمات است.--> 
              <a href="{% url 'blog:single' pid=post.id %}" class="primary-btn">View More</a>
            </div>
          </div>
          {% endfor %}
          <nav class="blog-pagination justify-content-center d-flex">                                     
            <ul class="pagination">
                            <!--
                        <a href="?page=1">&laquo; first</a>
                        <a href="?page={{ page_obj.previous_page_number }}">previous</a>
                            -->
              {% if posts.has_previous %}
              <li class="page-item">
                <a href="?page={{ posts.previous_page_number }}" class="page-link" aria-label="Previous"><span aria-hidden="true"><span class="lnr lnr-chevron-left"></span></span></a>
              </li>
              {% endif %}

              
              <!--         
              <li class="page-item active">
                <a href="#" class="page-link">02</a>
              </li>
              -->     

              {% for i in posts.paginator.page_range %}
              {% if posts.number == i %}
              <li class="page-item active">
                <a href="?page={{i}}" class="page-link">{{i}}</a>
              </li>
              {% else %}
              <li class="page-item">
                <a href="?page={{i}}"  class="page-link">{{i}}</a>
              </li>
              {% endif %}
              {% endfor %}

              {% if posts.has_next %}
                <!--<a href="?page={{ posts.next_page_number }}">next</a>
                <a href="?page={{ posts.paginator.num_pages }}">last &raquo;</a>-->
                  
              <li class="page-item">
                <a href="?page={{ posts.next_page_number }}" class="page-link" aria-label="Next"><span aria-hidden="true"><span class="lnr lnr-chevron-right"></span></span></a>
              </li>
              {% endif %}
            </ul>
          </nav>
        </div>
        <div class="col-lg-4 sidebar-widgets">
          <div class="widget-wrap">

            {% include "blog/blog-search.html" %}

            {% include "blog/blog-writer.html" %}

            {% latest_posts %}

            {% include "blog/blog-ads.html" %}

            {% post_categories %}

            {% include "blog/blog-newsletter.html" %}

            {% include "blog/blog-tags-cloud.html" %}

          </div>
        </div>
      </div>
    </div>
  </section>
  <!-- End post-content Area -->
{% endblock %}

templates/blog/blog-latest-posts.html
{% load static %}
{% load humanize %}
{% load blog_tags %}
<div class="single-sidebar-widget popular-post-widget">
    <h4 class="popular-title">Latest Posts</h4>
    <div class="popular-post-list">
        {% for post in posts %}
    <div class="single-post-list d-flex flex-row align-items-center">
        <div class="thumb">
        <img class="img-fluid" src="{{post.image.url}}" alt="" />
        </div>
        <div class="details">
        <a href='{% url 'blog:single' pid=post.id %}'><h6>{{post.title}}</h6></a>
        <p>{{post.published_date|date:'d M Y'}}</p>
        <p>{{post.published_date|naturaltime}}</p>            <!-- django.contrib.humanize inja ro toye site ha save kardam ke model haye mokhtalefiye ke roye adad ha mishe kar kard va humanize kardeshon ke khoshgel tar va ensani tar shan toye setting installed app ham add shode -->
        </div>                                                <!-- hatman lazeme ke bala load humanize ro benevisim -->                                                              
    </div>                                                    <!-- inja ham yek pip dige install kardim ke komak konandas ke inam to save haye site ha save kardam be esm django-extentions ke to installed app setting ham add kardam -->
        {% endfor %}

    </div>
</div>

templates/blog/blog-newsletter.html
<div class="single-sidebar-widget newsletter-widget">
    <h4 class="newsletter-title">Newsletter</h4>
    <p>Here, I focus on a range of items and features that we use in life without giving them a second thought.</p>
    <div class="form-group d-flex flex-row">
    <div class="col-autos">
        <div class="input-group">
        <div class="input-group-prepend">
            <div class="input-group-text">
            <i class="fa fa-envelope" aria-hidden="true"></i>
            </div>
        </div>
        <input type="text" class="form-control" id="inlineFormInputGroup" placeholder="Enter email" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter email'" />
        </div>
    </div>
    <a href="#" class="bbtns">Subcribe</a>
    </div>
    <p class="text-bottom">You can unsubscribe at any time</p>
</div>

templates/blog/blog-post-categories.html
<div class="single-sidebar-widget post-category-widget">
    <h4 class="category-title">Post Catgories</h4>
    <ul class="cat-list">
        {% for name,count in categories.items %}
    <li>
        <a href="{% url 'blog:category' cat_name=name %}" class="d-flex justify-content-between">
        <p>{{name}}</p>
        <p>{{count}}</p>
        </a>
    </li>
        {% endfor %}
    </ul>
</div>

templates/blog/blog-search.html
<div class="single-sidebar-widget search-widget">
<form class="search-form" action="{% url 'blog:search' %}" method="GET">
    <input placeholder="Search Posts" name="s" type="text" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Search Posts'" />
    <button type="submit"><i class="fa fa-search"></i></button>
</form>
</div>

templates/blog/blog-single.html
{% extends 'base.html' %}
{% load static %}
{% load blog_tags %}
{% load humanize %}
{% block content %}
  <!-- start banner Area -->
  <section class="relative about-banner">
    <div class="overlay overlay-bg"></div>
    <div class="container">
      <div class="row d-flex align-items-center justify-content-center">
        <div class="about-content col-lg-12">
          <h1 class="text-white">{{post.title}}</h1>
          <p class="text-white link-nav">
            <a href="{% url "website:index" %}">Home</a> <span class="lnr lnr-arrow-right"></span><a href={% url "blog:home" %}>Blog</a> <span class="lnr lnr-arrow-right"></span>{{post.title}}</a>
          </p>
        </div>
      </div>
    </div>
  </section>
  <!-- End banner Area -->

  <!-- Start post-content Area -->
  <section class="post-content-area single-post-area">
    <div class="container">
      <div class="row">
        <div class="col-lg-8 posts-list">
							<div class="single-post row">
								<div class="col-lg-12">
									<div class="feature-img">
										<img class="img-fluid" src="{{post.image.url}}" alt="">
									</div>									
								</div>
								<div class="col-lg-3  col-md-3 meta-details">
									<ul class="tags">
                {% for cat in post.category.all %}
                <li>
                  <a href="{% url 'blog:category' cat_name=cat.name %}">{{ cat.name }}</a>{% if not forloop.last %}, {% endif %}</a>
                </li>
                {% endfor %}
									</ul>
									<div class="user-details row">
										<p class="user-name col-lg-12 col-md-12 col-6"><a href="#">{{post.author}}</a> <span class="lnr lnr-user"></span></p>
										<p class="date col-lg-12 col-md-12 col-6"><a href="#">{{post.published_date|date:'m/d/Y'}}</a> <span class="lnr lnr-calendar-full"></span></p>
										<p class="view col-lg-12 col-md-12 col-6"><a href="#">{{post.counted_view}}</a> <span class="lnr lnr-eye"></span></p>
										<p class="comments col-lg-12 col-md-12 col-6"><a href="#">{{comments|length}} Comments</a> <span class="lnr lnr-bubble"></span></p>
										<ul class="social-links col-lg-12 col-md-12 col-6">
											<li><a href="#"><i class="fa fa-facebook"></i></a></li>
											<li><a href="#"><i class="fa fa-twitter"></i></a></li>
											<li><a href="#"><i class="fa fa-github"></i></a></li>
											<li><a href="#"><i class="fa fa-behance"></i></a></li>
										</ul>																				
									</div>
								</div>
								<div class="col-lg-9 col-md-9">
									<h3 class="mt-20 mb-20">{{post.title}}</h3>
									<p class="excert">
										{{post.content|safe}}  <!-- safe baes mishe ke bezare ke ma age khastim betonim edit konim html ro toye admin site -->
									</p>
								</div>
							</div>
          <div class="navigation-area">
            <div class="row">
              {% if prev_post %}
              <div class="col-lg-6 col-md-6 col-12 nav-left flex-row d-flex justify-content-start align-items-center">
                <div class="thumb">
                  <a href="{% url 'blog:single' prev_post.id %}"><img class="img-fluid" src="{{prev_post.image.url}}" alt="" /></a>
                </div>
                <div class="arrow">
                  <a href="{% url 'blog:single' prev_post.id %}"><span class="lnr text-white lnr-arrow-left"></span></a>
                </div>
                <div class="detials">
                  <p>Prev Post</p>
                  <a href="{% url 'blog:single' prev_post.id %}"><h4>{{prev_post.title}}</h4></a>
                </div>
              </div>
              {% else %}
                <div class="col-lg-6 col-md-6 col-12 nav-left flex-row d-flex justify-content-start align-items-center">
                <div class="detials">
                </div>
              </div>
              {% endif %}
              {% if next_post %}
              <div class="col-lg-6 col-md-6 col-12 nav-right flex-row d-flex justify-content-end align-items-center">
                <div class="detials">
                  <p>Next Post</p>
                  <a href="{% url 'blog:single' next_post.id %}"><h4>{{next_post.title}}</h4></a>
                </div>
                <div class="arrow">
                  <a href="{% url 'blog:single' next_post.id %}"><span class="lnr text-white lnr-arrow-right"></span></a>
                </div>
                <div class="thumb">
                  <a href="{% url 'blog:single' next_post.id %}"><img class="img-fluid" src="{{next_post.image.url}}" alt="" /></a>
                </div>
              </div>
              {% else %}
                <div class="col-lg-6 col-md-6 col-12 nav-left flex-row d-flex justify-content-start align-items-center">
                <div class="detials">
                </div>
              </div>
              {% endif %}
            </div>
          </div>

          <div class="comments-area">
            <div id="disqus_thread"></div>
              <script>
                  (function() { 
                  var d = document, s = d.createElement('script');
                  s.src = 'https://training-11.disqus.com/embed.js';
                  s.setAttribute('data-timestamp', +new Date());
                  (d.head || d.body).appendChild(s);
                  })();
              </script>
              <noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
          </div>

          <div class="comments-area">
            <h4>{{ comments|length }} comments</h4>
            {% if comments|length %}
            {% for comment in comments %}
            <div class="comment-list">
              <div class="single-comment justify-content-between d-flex">
                <div class="user justify-content-between d-flex">
                  <div class="thumb">
                    <img src="{% static 'img/blog/c1.jpg' %}" alt="" />
                  </div>
                  <div class="desc">
                    <h3><a href="#">{{comment.name}}</a></h3>
                    <p class="date">{{comment.created_date|naturalday}}</p>
                    <h5 class="subject">{{comment.subject}}</h5>
                    <p class="message">{{comment.message}}</p>
                  </div>
                </div>
              </div>
            </div>
            {% endfor %}
            {% else %}
              <a>no comments here be the first one to comment </a>
            {% endif %}
          </div> 
          
          <div class="comment-form">
            <h4>Leave a Comment</h4>
            <form method="post" action='{% url "blog:single" pid=post.id %}'>
              {% csrf_token %}
              <input type="hidden" name="post" value={{post.id}}>
              {% if request.user.is_authenticated %}
                <input type="hidden" name="name" value={{request.user.first_name}}>
                <input type="hidden" name="email" value={{request.user.email}}>
              {% else %}
              <div class="form-group form-inline">
                <div class="form-group col-lg-6 col-md-12 name">
                  <input type="text" class="form-control" name="name" placeholder="Enter Name" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter Name'" />
                </div>
                <div class="form-group col-lg-6 col-md-12 email">
                  <input type="email" class="form-control" name="email" placeholder="Enter email address" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter email address'" />
                </div>
              </div>
              {% endif %}
              <div class="form-group">
                <input type="text" class="form-control" name="subject" placeholder="Subject" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Subject'" />
              </div>
              <div class="form-group">
                <textarea class="form-control mb-10" rows="5" name="message" placeholder="Messege" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Messege'" required=""></textarea>
              </div>

              <button type='submit' href="#" class="primary-btn text-uppercase">Post Comment</a>
            </form>
          </div>
        </div>


        <div class="col-lg-4 sidebar-widgets">
          <div class="widget-wrap">

            {% include "blog/blog-search.html" %}

            {% include "blog/blog-writer.html" %}

            {% latest_posts %}

            {% include "blog/blog-tags-cloud.html" %}

            {% post_categories %}

            {% include "blog/blog-ads.html" %}

            {% include "blog/blog-newsletter.html" %}
            
          </div>
        </div>
      </div>
    </div>
  </section>
  <!-- End post-content Area -->
{% endblock %}

templates/blog/blog-tags-cloud.html
<div class="single-sidebar-widget tag-cloud-widget">
    <h4 class="tagcloud-title">Tag Clouds</h4>
    <ul>
       {% for tag in post.tags.all %}
            <li>
                <a href="{% url 'blog:tag' tag_name=tag.name %}">{{tag.name}}</a>
            </li>
       {% endfor %}
    </ul>
</div>

templates/blog/blog-writer.html
{% load static %}

            <div class="single-sidebar-widget user-info-widget">
              <img src="{% static 'img/blog/user-info.png' %}" alt="" />
              <a href="#"><h4>Charlie Barber</h4></a>
              <p>Senior blog writer</p>
              <ul class="social-links">
                <li>
                  <a href="#"><i class="fa fa-facebook"></i></a>
                </li>
                <li>
                  <a href="#"><i class="fa fa-twitter"></i></a>
                </li>
                <li>
                  <a href="#"><i class="fa fa-github"></i></a>
                </li>
                <li>
                  <a href="#"><i class="fa fa-behance"></i></a>
                </li>
              </ul>
              <p>Boot camps have its supporters andit sdetractors. Some people do not understand why you should have to spend money on boot camp when you can get. Boot camps have itssuppor ters andits detractors.</p>
            </div>